-- ============================================================
-- APT Behaviour Analysis — PostgreSQL Schema
-- ============================================================

-- Enable pgaudit extension if available (optional but recommended)
-- CREATE EXTENSION IF NOT EXISTS pgaudit;

-- Session-level tracking
CREATE TABLE IF NOT EXISTS apt_sessions (
    session_id   BIGSERIAL PRIMARY KEY,
    user_name    TEXT NOT NULL,
    client_addr  INET,
    start_time   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    end_time     TIMESTAMPTZ,
    backend_pid  INTEGER,        -- Linux PID of the Postgres backend
    origin_process TEXT,         -- Resolved OS process name (e.g., psql, bash)
    threat_label INTEGER DEFAULT 0  -- 0=benign, 1=suspicious, 2=APT
);

-- Individual query events within a session
CREATE TABLE IF NOT EXISTS apt_events (
    event_id        BIGSERIAL PRIMARY KEY,
    session_id      BIGINT REFERENCES apt_sessions(session_id) ON DELETE CASCADE,
    event_time      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    command_type    TEXT NOT NULL,   -- SELECT, INSERT, UPDATE, DELETE, COPY, ALTER, GRANT …
    object_schema   TEXT,
    object_name     TEXT,
    rows_affected   INTEGER DEFAULT 0,
    query_hash      TEXT,            -- MD5 of normalised query
    duration_ms     FLOAT DEFAULT 0
);

-- Alerts generated by the DQL agent
CREATE TABLE IF NOT EXISTS apt_alerts (
    alert_id     BIGSERIAL PRIMARY KEY,
    session_id   BIGINT REFERENCES apt_sessions(session_id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    threat_score FLOAT NOT NULL,
    action_taken TEXT NOT NULL,    -- 'alert', 'rate_limit', 'block'
    q_values     TEXT,             -- JSON string of [Q0, Q1, Q2, Q3]
    resolved     BOOLEAN DEFAULT FALSE
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_events_session   ON apt_events(session_id);
CREATE INDEX IF NOT EXISTS idx_events_time      ON apt_events(event_time);
CREATE INDEX IF NOT EXISTS idx_alerts_session   ON apt_alerts(session_id);
CREATE INDEX IF NOT EXISTS idx_alerts_time      ON apt_alerts(created_at);
